services:
  mysql:
    image: mohdarslan/mysql-with-schema:3.0

    env_file:
      - .env

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - backend

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s


  flask-app:
    image: mohdarslan/flask-app:secure

    env_file:
      - .env

    ports:
      - "5000:5000"

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - backend

    restart: unless-stopped

    tmpfs:
      - /tmp

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:

